logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: OFF
    org.springframework.web.HttpLogging: OFF

service:
  address:
    auth: 'localhost:3000'
    bill: 'localhost:3000'
    delivery: 'localhost:3000'
